### PR TITLE
Update os_sudoers.j2

### PR DESCRIPTION
**Pull request by lucamaf**
let people in wheel run any command otherwise I'll lose access before being able to remove the following option (without password)

### CODE REVIEW

**Comment by luisarizmendi** [comment]
@lucamaf the sudoers file is intentional. 

In the config file you can find that it's allowed to run sudo commands without password (`%wheel ALL=(ALL) NOPASSWD: ALL`) while the default that asks for password (`#%wheel ALL=(ALL) ALL`) is commented out, so when a new device joins the AAP you will get the enforcement of this non-recommended setup (because AAP onboarding workflow is changing the /etc/host file then the python notify will start that enforcement).

 Since the devices have a non-recommended configuration you "have to" configure it in the right way during the demo by just changing this file in GITEA.

You could do it in the other way round, you could let the default asking for a password and during the demo configuring the sudoers to not asking for a password but what you shouldn't do is leaving both uncommented.

**Comment by lucamaf** [comment]
completely agree and it was working as you suggested during the demo, except during the last run for some unknown reason it applied the a part of the configuration before all the file was changed (specifically it commented out both lines at the same time) which resulted in losing access as admin to the Edge device. Not sure if that happen to you as well ?

**Comment by luisarizmendi** [comment]
That's not normal, because either the sudoers file on git is applied or not. Maybe the problem is that it was not applied and the device keep the "manual overwritten" config (which might have both commented out).

This could happen if you perform two modifications while EDA is applying back the changes. This is because I implemented a very simple way to lock further requests to the EDA API when there is a change: it creates a temp file. When AAP applies back the config it removes that file so the requests start flowing again. If that file was not removed by AAP (for whatever reason) then the git file was not applied.  This is not the best way but it works for the demo....

**Comment by lucamaf** [comment]
got it , possibly my mistake applying two modifications one after the other, closing this as explained

**Pull request closed without merging**
